# Generated by Django 2.1.2 on 2018-10-12 13:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmModel',
            fields=[
                ('adult', models.BooleanField(null=True)),
                ('belongs_to_collection', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('budget', models.IntegerField(null=True)),
                ('genres', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('homepage_url', models.URLField(null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imdb_id', models.CharField(max_length=100, null=True)),
                ('original_language', models.CharField(max_length=64, null=True)),
                ('original_title', models.TextField(null=True)),
                ('overview', models.TextField(null=True)),
                ('popularity', models.FloatField(null=True)),
                ('poster_path', models.URLField(null=True)),
                ('production_companies', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('production_countries', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('runtime', models.FloatField(null=True)),
                ('spoken_languages', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('revenue', models.FloatField(null=True)),
                ('status', models.CharField(max_length=32, null=True)),
                ('tagline', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('video', models.BooleanField(null=True)),
                ('vote_average', models.FloatField(null=True)),
                ('vote_count', models.IntegerField(null=True)),
            ],
        ),
    ]
