# Generated by Django 2.1.2 on 2018-10-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmmodel',
            old_name='homepage_url',
            new_name='homepage',
        ),
    ]
