# Generated by Django 2.1.2 on 2018-10-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181012_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmmodel',
            name='overview',
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
