# Generated by Django 2.1.2 on 2018-10-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181012_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmmodel',
            name='original_language',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='filmmodel',
            name='status',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
