# Generated by Django 2.1.2 on 2018-10-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181012_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmmodel',
            name='overview',
            field=models.TextField(null=True),
        ),
    ]
