# Generated by Django 2.1.2 on 2018-10-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181012_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmmodel',
            name='homepage',
            field=models.URLField(max_length=1024, null=True),
        ),
    ]
