# Generated by Django 2.1.2 on 2018-10-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181012_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmmodel',
            name='adult',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='filmmodel',
            name='video',
            field=models.NullBooleanField(),
        ),
    ]
