# Generated by Django 2.1.2 on 2018-10-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20181013_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmmodel',
            name='genres',
            field=models.ManyToManyField(null=True, related_name='genres', to='main.FilmGenre'),
        ),
        migrations.AlterField(
            model_name='filmmodel',
            name='production_countries',
            field=models.ManyToManyField(null=True, related_name='production_countries', to='main.ProductionCountry'),
        ),
    ]
