# Generated by Django 2.1.2 on 2018-10-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20181013_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmgenre',
            name='films',
        ),
        migrations.RemoveField(
            model_name='productioncountry',
            name='films',
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='genres',
            field=models.ManyToManyField(to='main.FilmGenre'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='production_countries',
            field=models.ManyToManyField(to='main.ProductionCountry'),
        ),
    ]
